defaults:
  agents: &default-agents
    queue: voice-app-builder-v2
  plugins: &default-plugins
    - first-aml/git-clone:
        repository: https://github.com/voice-social/voice-buildkite-template.git

steps:
  # - label: ":buildkite: Trigger API build"
  #   trigger: hyperion-history-api
  #   if: build.tag == null && build.branch == "master" && build.pull_request.id == null
  #   build:
  #     message: "${BUILDKITE_MESSAGE}"
  - command:
      - cd .. && git clone https://github.com/voice-social/hyperion-history-api.git
      - ln -s hyperion-explorer-plugin hyperoin-history-api/plugins/repos
      - cd hyperion-history-api && npm install && ./hpm build all
    artifact_paths:
      - ../hyperion-history-api/repos/explorer/*
    agents: *default-agents
