defaults:
  agents: &default-agents
    queue: voice-app-builder-v2
  plugins: &default-plugins
    - first-aml/git-clone:
        repository: https://github.com/voice-social/voice-buildkite-template.git

steps:
  # - label: ":buildkite: Trigger API build"
  #   trigger: hyperion-history-api
  #   if: build.tag == null && build.branch == "master" && build.pull_request.id == null
  #   build:
  #     message: "${BUILDKITE_MESSAGE}"
  - command:

      - "git clone https://github.com/voice-social/hyperion-history-api.git \
         && cd hyperion-history-api \
         && npm install && ./hpm install -r https://github.com/voice-social/hyperion-explorer-plugin.git explorer \
         && cd .. && tar -zcvf explorer.tar.gz /buildkite/builds/${BUILDKITE_AGENT_NAME}/hyperion-explorer-plugin/hyperion-history-api/plugins/repos/explorer"
    artifact_paths:
      - explorer.tar.gz
    agents: *default-agents
